arch: amd64
dist: trusty
language: go
go:
  - 1.12.x
before_install:
  - export GO111MODULE=on
before_script:
  - |
    if [ -z "$TRAVIS_TAG" ]; then
      export TARGET_NAME=sonar-qyhook-dev
    else
      export TARGET_NAME=sonar-qyhook-$TRAVIS_TAG
    fi
script:
  - echo "building "$TARGET_NAME" ..."
  - env GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o $TARGET_NAME.linux.386.bin
  - env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o $TARGET_NAME.linux.amd64.bin
  - env GOOS=darwin GOARCH=386 go build -ldflags="-s -w" -o $TARGET_NAME.darwin.386.bin
  - env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o $TARGET_NAME.darwin.amd64.bin
  - env GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o $TARGET_NAME.windows.386.exe
  - env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o $TARGET_NAME.windows.amd64.exe
before_deploy:
  - wget https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz
  - tar -xvJf upx-3.95-amd64_linux.tar.xz
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.linux.386.bin
  - tar -cvJf $TARGET_NAME.linux.386.tar.xz $TARGET_NAME.linux.386.bin
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.linux.amd64.bin
  - tar -cvJf $TARGET_NAME.linux.amd64.tar.xz $TARGET_NAME.linux.amd64.bin
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.darwin.386.bin
  - tar -cvJf $TARGET_NAME.darwin.386.tar.xz $TARGET_NAME.darwin.386.bin
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.darwin.amd64.bin
  - tar -cvJf $TARGET_NAME.darwin.amd64.tar.xz $TARGET_NAME.darwin.amd64.bin
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.windows.386.exe
  - tar -cvJf $TARGET_NAME.windows.386.tar.xz $TARGET_NAME.windows.386.exe
  - ./upx-3.95-amd64_linux/upx --brute $TARGET_NAME.windows.amd64.exe
  - tar -cvJf $TARGET_NAME.windows.amd64.tar.xz $TARGET_NAME.windows.amd64.exe
deploy:
  provider: releases
  api_key:
    secure: Sn/xZUTVFn6e4pHffTMBeJkVaacGWIzIhMsjWSmMocJ39Zwo/KNGHNARCD2s4J3xF9Snju8pW2xSYEfUogXhpTxJaSHM1ecb9b2h2jv+7nWV9SrSqRkglTuBM3M8+6e4ezUla3qvBhE1tB3pZyvVOjkCYEbdeLfxlLiyrMbQkuKvV/qEc/5uBB35Q44nYm86fQut8Vqun3RuHrNKCS2eR7CoDBSV+p5F1PcOX1IdZdYHR3ewGvvxJ61EqNtz2Y4jQD9bkSe8IliY3ewUW5nP2l6ckcqJcy3NkUJhCUBo/+EUpff2YALQE+wMzCLFIiHbFsfoSmuwS+xmfT2FVBFYNgZzM7hNFjpydGn6+Z7OUgOt0nzSwMYKoYvDU+i54IqesrauZALZ5Rt70rCBS9lTCaWbzlvBfqhYBup7Fapv40uKQ4lCzkR+dC7Ues+TEacp6Pex6xblzYJ8RPTpyOCDKDkaE1BrM8cHF+gek2lY8QNPo5wWzAeopRCmgtG+lZ3DH4OJZIbL+V9Pw8wvks655TItZIHSuve/nxGOntScchm9KEu3zWr4E0fyLtgHWxO+k1HlpNfTRUGFJaOQPTzj8CUV0KB2mzB9kUfMVKXKkOqCNxvmiO3Q3q1e4pIkwTXMe8cZdGWloPSLsrluxl8i/rIbY71rJBpawasa+e8SojY=
  file_glob: true
  file: $TARGET_NAME.*.tar.xz
  skip_cleanup: true
  on:
    repo: CharLemAznable/sonar-qyhook
    tags: true
